---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: postgres
    port: {{ .Values.container.port.db }}
  selector:
    app: mydb
  type: {{ .Values.service.type.db }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: frontend
    port: 8000
    targetPort: {{ .Values.container.port.frontend }}
    protocol: TCP
  selector:
    app: frontend
  type: {{ .Values.service.type.frontend }}
  