all:
  hosts:
    master1:
      ansible_host: 10.130.0.9
      ip: 10.130.0.9
      access_ip: 10.130.0.9
    node1:
      ansible_host: 10.130.0.6
      ip: 10.130.0.6
      access_ip: 10.130.0.6
    node2:
      ansible_host: 10.130.0.26
      ip: 10.130.0.26
      access_ip: 10.130.0.26
    node3:
      ansible_host: 10.130.0.24
      ip: 10.130.0.24
      access_ip: 10.130.0.24
    node4:
      ansible_host: 10.130.0.28
      ip: 10.130.0.28
      access_ip: 10.130.0.28
  children:
    kube_control_plane:
      hosts:
        master1:
    kube_node:
      hosts:
        master1:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
